"""Ecommerce, SaaS, and developer-tool vocabulary."""

ECOMMERCE = [
    # --- metrics ---
    ("AOV", [], 1, "Total revenue divided by number of orders. What a typical customer spends per purchase."),
    ("LTV", ["lifetime value", "CLV"], 1, "The total revenue expected from a customer across the whole relationship."),
    ("CAC", [], 1, "The total sales and marketing spend required to acquire one new customer."),
    ("ROAS", [], 1, "Revenue generated per unit of ad spend. A channel efficiency measure."),
    ("contribution margin", [], 2, "Revenue less all variable costs, including fulfilment and returns. What a sale actually leaves behind."),
    ("cart abandonment", [], 2, "When a shopper adds items then leaves without buying. Tracked as a percentage of carts created."),
    ("checkout abandonment", [], 2, "Leaving after starting checkout rather than at the cart. Usually a friction or trust problem, not a pricing one."),
    ("repeat purchase rate", [], 2, "The share of customers who buy more than once. The clearest early signal of retention."),
    ("returns rate", [], 1, "The share of orders sent back. A direct drag on contribution margin."),
    ("sell-through rate", [], 2, "Units sold as a share of units received in a period. An inventory efficiency measure."),
    ("attach rate", [], 2, "How often an accessory or add-on sells alongside a primary product."),
    ("GMV", [], 1, "Gross merchandise value. Total sales value transacted, before fees, returns, or discounts."),

    # --- catalog ---
    ("SKU", [], 1, "A unique identifier for one distinct sellable item, including its size and colour variant."),
    ("GTIN", ["UPC", "EAN"], 2, "A global trade item number identifying a product across retailers. Required for many shopping feeds."),
    ("MPN", [], 2, "Manufacturer part number. Identifies a product as the maker designates it."),
    ("variant", [], 2, "A version of a product differing by one attribute such as size or colour. A frequent duplicate-content source."),
    ("parent product", [], 2, "The grouping record that variants belong to. Usually the URL you want indexed."),
    ("product feed", ["merchant feed"], 2, "A structured file of catalog data submitted to shopping channels so they can list your items."),
    ("category taxonomy", [], 2, "The hierarchy products are organized into. Drives both navigation and crawl efficiency."),
    ("attribute enrichment", [], 2, "Filling out product attributes so items are filterable, comparable, and retrievable."),
    ("catalog hygiene", [], 2, "Keeping titles, attributes, images, and availability accurate across a large catalog."),
    ("PIM", [], 2, "Product information management. The system holding canonical product data feeding storefronts and channels."),
    ("out of stock", [], 2, "An unavailable item. How you handle the page matters: keeping and updating it usually beats removing it."),
    ("backorder", [], 2, "Accepting an order for stock not yet held, to be fulfilled on arrival."),
    ("discontinued product", [], 2, "An item no longer sold. Redirect to the nearest replacement rather than returning a 404."),

    # --- pages ---
    ("PDP", [], 1, "The page for a single product, carrying its description, images, price, and availability."),
    ("PLP", ["category page"], 1, "A page listing multiple products, usually filterable and paginated."),
    ("collection page", [], 2, "A curated grouping of products, often built for a theme or campaign rather than the core taxonomy."),
    ("Product schema", [], 2, "Structured data describing an item's price, availability, and reviews, enabling enriched shopping results."),
    ("review schema", [], 2, "Structured data exposing ratings and reviews, commonly rendered as stars in results."),
    ("UGC", ["user generated content"], 2, "Reviews, photos, and questions contributed by customers. Cheap, distinctive content that is hard for competitors to copy."),
    ("buying guide", [], 2, "Editorial content helping a shopper choose between options. Captures upper-funnel intent that product pages cannot."),

    # --- operations ---
    ("merchandising", [], 2, "Deciding which products surface where, in what order, to steer discovery and margin."),
    ("marketplace", [], 2, "A platform selling third-party inventory alongside or instead of its own."),
    ("dropshipping", [], 2, "Selling goods fulfilled directly by a supplier, so the retailer never holds stock."),
    ("3PL", [], 2, "Third-party logistics. An outside provider handling warehousing and fulfilment."),
    ("fulfilment", [], 2, "Picking, packing, and shipping an order after it is placed."),
    ("last mile", [], 2, "The final delivery leg to the customer. Usually the most expensive part of shipping."),
    ("BOPIS", [], 2, "Buy online, pick up in store. A fulfilment option blending ecommerce and physical retail."),
    ("inventory turnover", [], 2, "How many times stock is sold and replaced in a period."),
    ("stockout", [], 2, "Demand arriving with no inventory to meet it. Costs the sale and often the customer."),
    ("safety stock", [], 2, "Buffer inventory held to absorb demand variability and supplier delay."),

    # --- pricing and promotion ---
    ("price parity", [], 2, "Keeping a product's price consistent across the channels you sell on."),
    ("MAP", [], 2, "Minimum advertised price. A supplier-set floor on the price resellers may display."),
    ("dynamic pricing", [], 2, "Adjusting price automatically in response to demand, competition, or inventory."),
    ("markdown", [], 2, "A permanent price reduction, usually to clear ageing inventory."),
    ("basket analysis", ["market basket analysis"], 2, "Studying which products are bought together to inform bundling and recommendations."),
    ("subscription commerce", [], 2, "Selling on a recurring schedule rather than one purchase at a time."),
    ("loyalty program", [], 2, "A structured incentive rewarding repeat purchase."),

    # --- payments and channels ---
    ("chargeback", [], 2, "A forced reversal of a card payment initiated by the cardholder's bank."),
    ("payment gateway", [], 2, "The service authorizing and processing card payments at checkout."),
    ("BNPL", [], 2, "Buy now, pay later. Instalment financing offered at checkout."),
    ("headless commerce", [], 2, "Separating the storefront presentation layer from the commerce backend, connected by APIs."),
    ("omnichannel", [], 2, "Treating online, mobile, and physical retail as one continuous customer experience."),
    ("agentic commerce", [], 2, "Purchases discovered, negotiated, or completed by an AI agent acting for a shopper."),
    ("conversational commerce", [], 2, "Selling through chat, messaging, or assistant interfaces rather than a browsing storefront."),
]

SAAS = [
    # --- revenue ---
    ("ARR", [], 1, "Contracted subscription revenue normalized to a yearly figure."),
    ("MRR", [], 1, "Contracted subscription revenue normalized to a monthly figure."),
    ("churn", ["churn rate"], 1, "The share of customers or revenue lost in a period."),
    ("logo churn", [], 2, "Churn counted by number of customers rather than by revenue."),
    ("revenue churn", [], 2, "Churn counted by lost revenue. Can differ sharply from logo churn if losses skew large or small."),
    ("NRR", ["net revenue retention"], 2, "Revenue from existing customers this period versus last, including expansion and churn. Above 100% means growth without new logos."),
    ("GRR", ["gross revenue retention"], 2, "Retention excluding expansion. Shows the true floor beneath a revenue base."),
    ("expansion revenue", [], 2, "Additional revenue from existing customers through upgrades, seats, or usage."),
    ("CAC payback", [], 2, "How long it takes gross margin from a customer to repay their acquisition cost."),
    ("magic number", [], 2, "A sales efficiency ratio comparing new ARR to the sales and marketing spend that produced it."),
    ("rule of 40", [], 2, "A heuristic that growth rate plus profit margin should exceed forty."),
    ("burn multiple", [], 2, "Net cash burned per unit of net new ARR. A capital efficiency measure."),

    # --- funnel ---
    ("PQL", [], 2, "Product qualified lead. A user whose product usage signals readiness to buy, as opposed to one who filled in a form."),
    ("MQL", [], 2, "Marketing qualified lead. A contact judged ready for sales follow-up based on marketing engagement."),
    ("SQL", ["sales qualified lead"], 2, "A lead sales has accepted as worth pursuing."),
    ("product-led growth", ["PLG"], 2, "Acquiring and expanding customers through the product itself rather than through a sales motion."),
    ("sales-led growth", [], 2, "Acquiring customers primarily through outbound and direct selling."),
    ("free trial", [], 2, "Time-limited full access used to demonstrate value before purchase."),
    ("freemium", [], 2, "A permanently free tier with paid upgrades, as distinct from a time-limited trial."),
    ("self-serve", [], 2, "A purchase path a customer completes without talking to sales."),
    ("activation", [], 2, "The point where a new user first reaches meaningful value. The metric that most predicts retention."),
    ("time to value", ["TTV"], 2, "How long it takes a new user to reach that first meaningful outcome."),
    ("onboarding", [], 2, "The guided path from signup to first value."),
    ("aha moment", [], 2, "The specific action correlating most strongly with a user becoming retained."),
    ("seat expansion", [], 2, "Growth in revenue from adding users within an existing account."),

    # --- technical ---
    ("API", [], 1, "A defined contract letting one system call another programmatically."),
    ("REST", [], 1, "An API style using standard HTTP verbs against resource URLs."),
    ("GraphQL", [], 1, "A query language letting a client request exactly the fields it needs in one round trip."),
    ("webhook", [], 2, "An outbound HTTP callback fired when an event occurs, so consumers do not have to poll."),
    ("rate limit", [], 2, "A cap on how many requests a client may make in a window."),
    ("idempotency", [], 2, "A property where repeating a request produces the same result. Essential for safe retries."),
    ("SDK", [], 1, "A language-specific library wrapping an API so developers do not hand-roll requests."),
    ("OAuth", [], 2, "A standard letting an application access an account without handling the password."),
    ("SSO", [], 2, "Single sign-on. Authenticating once against an identity provider to access multiple applications."),
    ("SCIM", [], 2, "A standard for automatically provisioning and deprovisioning user accounts."),
    ("multi-tenancy", [], 2, "One application instance serving many customers with their data isolated."),
    ("sandbox", [], 2, "An isolated environment for testing against an API without touching production data."),
    ("deprecation", [], 2, "Marking an API feature for removal, with a window for consumers to migrate."),
    ("versioning", [], 2, "Publishing distinct API versions so changes do not break existing integrations."),
    ("uptime SLA", [], 2, "A contractual availability commitment, usually with credits owed when it is missed."),
    ("latency", [], 1, "The delay between a request and its response."),

    # --- product and go to market ---
    ("developer experience", ["DX"], 2, "How easily a developer can adopt and succeed with a tool. A genuine differentiator in this category."),
    ("documentation site", ["docs"], 2, "The reference and guide content developers rely on. Often a product's highest-intent organic traffic."),
    ("changelog", [], 2, "A dated record of releases and changes."),
    ("usage-based pricing", [], 2, "Charging by consumption rather than a flat seat fee."),
    ("seat-based pricing", [], 2, "Charging per user, regardless of how much each uses."),
    ("feature gating", [], 2, "Restricting capabilities to particular plan tiers."),
    ("design partner", [], 2, "An early customer who shapes a product in exchange for access and influence."),
    ("integration marketplace", [], 2, "A directory of third-party connections, often a significant organic acquisition channel."),
    ("SOC 2", [], 2, "An audit report on security and availability controls. Frequently required in enterprise procurement."),
    ("penetration test", ["pentest"], 2, "An authorized simulated attack used to find exploitable weaknesses."),
    ("data residency", [], 2, "A commitment about which jurisdictions customer data is stored in."),
    ("procurement", [], 2, "The buyer-side process of security review, legal review, and approval before a contract is signed."),
    ("land and expand", [], 2, "Winning a small initial deployment then growing it across an organization."),
]
