"""Core search vocabulary, loaded on every site, plus agentic protocols."""

# (term, aliases, tier, definition)
# aliases are MATCH targets: text that genuinely appears in prose.
# acronym expansions live in EXPANSIONS and are display-only.

SEO_CORE = [
    # --- fundamentals ---
    ("SEO", ["search engine optimization"], 1, "Improving a site's visibility in organic search results through content, technical structure, and authority."),
    ("SERP", ["search engine results page"], 1, "The page of results returned for a query, including organic links, ads, and enriched features."),
    ("CTR", ["click-through rate"], 1, "The share of people who click a result after seeing it. Clicks divided by impressions."),
    ("impressions", [], 1, "The number of times a page appeared in search results, whether or not anyone clicked."),
    ("organic traffic", [], 1, "Visits arriving from unpaid search results."),
    ("search intent", ["user intent"], 2, "What a searcher is actually trying to accomplish. Usually grouped as informational, navigational, commercial, or transactional."),
    ("keyword research", [], 2, "Identifying the queries an audience uses, and the volume and competition behind each."),
    ("search volume", [], 1, "How many times a query is searched in a given period, usually monthly."),
    ("keyword difficulty", [], 2, "An estimate of how hard it is to rank for a query, usually derived from the authority of pages already ranking."),
    ("long tail", ["long-tail"], 2, "Low-volume, highly specific queries. Individually small, collectively the majority of search demand."),
    ("head term", [], 2, "A short, high-volume query. Competitive, and usually ambiguous in intent."),
    ("SERP feature", [], 2, "Any non-standard result element such as a featured snippet, knowledge panel, or People Also Ask block."),
    ("featured snippet", [], 2, "An answer extracted from a page and shown above the standard results."),
    ("People Also Ask", ["PAA"], 2, "The expandable related-question block in Google results. A useful map of sub-intents around a query."),
    ("knowledge panel", [], 2, "The entity summary box shown beside results, assembled from Google's knowledge graph."),
    ("local pack", ["map pack"], 2, "The map plus three business listings shown for local-intent queries."),
    ("zero-click search", [], 2, "A search resolved on the results page itself, so no site receives the visit."),
    ("cannibalization", ["keyword cannibalization"], 2, "Several pages on one site competing for the same query, splitting signals between them."),

    # --- technical ---
    ("crawling", [], 1, "The process of a search engine fetching pages from a site."),
    ("indexation", ["indexing"], 2, "Whether a page has been stored in a search engine's index and is therefore eligible to rank."),
    ("crawl budget", [], 2, "The number of pages a search engine will fetch from a site in a given period. Matters mainly at large scale."),
    ("crawl depth", [], 2, "How many clicks from the homepage a page sits. Deeper pages are crawled less often."),
    ("robots.txt", [], 2, "A root-level file telling crawlers which paths they may request. It controls crawling, not indexing."),
    ("noindex", [], 2, "A directive asking search engines to keep a page out of the index while still allowing it to be crawled."),
    ("nofollow", [], 2, "A link attribute telling search engines not to pass authority through that link."),
    ("canonical tag", ["rel=canonical"], 2, "A link element naming the preferred version of a page, used to consolidate duplicates onto one URL."),
    ("XML sitemap", ["sitemap.xml"], 2, "A machine-readable list of a site's URLs submitted to search engines to aid discovery."),
    ("redirect chain", [], 2, "Two or more redirects in sequence before reaching the final URL. Wastes crawl and leaks a little signal each hop."),
    ("301 redirect", [], 2, "A permanent redirect. Passes nearly all ranking signal to the destination."),
    ("302 redirect", [], 2, "A temporary redirect. Signals the original URL should stay indexed."),
    ("soft 404", [], 2, "A page that returns a success status while showing not-found content. Confuses indexing."),
    ("orphan page", [], 2, "A page with no internal links pointing to it, so crawlers and users can only reach it by direct URL."),
    ("faceted navigation", [], 2, "Filter-driven URLs on listing pages. A common source of near-duplicate pages and wasted crawl."),
    ("pagination", [], 2, "Splitting a long list across numbered pages. Needs care so crawlers reach deep items."),
    ("log file analysis", [], 2, "Reading server logs to see what crawlers actually requested, rather than what you assume they did."),
    ("hreflang", [], 2, "An annotation declaring the language and region a page targets, used to serve the right version internationally."),
    ("render budget", [], 2, "The limited resource search engines allocate to executing JavaScript before indexing a page."),
    ("client-side rendering", ["CSR"], 2, "Building page content in the browser with JavaScript. Adds a rendering step before content can be indexed."),
    ("server-side rendering", ["SSR"], 2, "Producing complete HTML on the server, so crawlers receive content without executing JavaScript."),
    ("static site generation", ["SSG"], 2, "Pre-building pages at deploy time. The most crawl-friendly rendering strategy."),
    ("hydration", [], 2, "Attaching JavaScript behaviour to server-rendered HTML in the browser."),
    ("mobile-first indexing", [], 2, "Google's use of the mobile version of a page as the primary basis for indexing and ranking."),

    # --- performance ---
    ("Core Web Vitals", ["CWV"], 2, "Google's page-experience metrics covering loading, interactivity, and layout stability."),
    ("LCP", [], 1, "How long the largest visible element takes to render. A loading-speed metric."),
    ("CLS", [], 1, "How much visible content moves unexpectedly during load. A visual-stability metric."),
    ("INP", [], 1, "How quickly a page responds to user interaction. Replaced First Input Delay."),
    ("TTFB", [], 1, "Time to first byte. How long the server takes to begin responding."),
    ("field data", ["CrUX"], 2, "Performance measured from real visitors, as opposed to a synthetic lab test."),
    ("lazy loading", [], 2, "Deferring off-screen resources until they are needed. Helps loading speed, hurts indexing if applied to primary content."),

    # --- structured data ---
    ("structured data", ["schema markup"], 2, "Machine-readable annotations stating what a page's content means, rather than leaving a parser to infer it."),
    ("JSON-LD", [], 1, "The JSON serialization of linked data, and the format search engines prefer for structured data."),
    ("schema.org", [], 2, "The shared vocabulary search engines use for structured data, maintained collaboratively by the major engines."),
    ("rich result", ["rich snippet"], 2, "An enhanced search listing showing extra detail such as ratings, prices, or FAQs, driven by structured data."),
    ("entity", [], 2, "A distinct thing a search engine can identify and hold facts about: a person, product, place, or organization."),
    ("knowledge graph", [], 2, "A search engine's database of entities and the relationships between them."),
    ("disambiguation", [], 2, "Resolving which entity a name refers to when several share it."),
    ("DefinedTerm", [], 2, "A schema.org type for a term and its definition, groupable into a DefinedTermSet."),
    ("breadcrumb", [], 2, "A trail showing a page's position in the site hierarchy. Often rendered directly in search results."),

    # --- content ---
    ("topic cluster", ["content hub"], 2, "A pillar page plus supporting pages on subtopics, interlinked to signal depth on a theme."),
    ("pillar page", [], 2, "The broad, central page of a topic cluster, linking out to its supporting detail pages."),
    ("content decay", [], 2, "The gradual traffic loss a page suffers as it ages and competitors publish fresher material."),
    ("content refresh", [], 2, "Updating an existing page rather than publishing a new one, usually the higher-return move."),
    ("content pruning", [], 2, "Removing or consolidating low-value pages to concentrate authority and reduce crawl waste."),
    ("thin content", [], 2, "A page with too little substance to satisfy the query it targets. Often generated at scale."),
    ("duplicate content", [], 2, "Substantially identical content at more than one URL, forcing engines to pick a version."),
    ("programmatic SEO", [], 2, "Generating many pages from a structured data source against a template. Powerful at scale, and the fastest route to thin content if unmanaged."),
    ("E-E-A-T", [], 2, "Experience, expertise, authoritativeness, and trust. Criteria in Google's quality rater guidelines, not a direct ranking factor."),
    ("YMYL", [], 2, "Your Money or Your Life. Topics where inaccuracy could cause real harm, held to a higher quality bar."),
    ("helpful content", [], 2, "Google's framing for material written primarily for people rather than for search engines."),
    ("title tag", [], 1, "The page title used as the clickable headline in search results."),
    ("meta description", [], 1, "A page summary search engines may use as the result snippet. Not a ranking factor, but it affects click-through."),
    ("H1", [], 1, "The primary heading of a page. One per page, describing what the page is about."),
    ("alt text", [], 2, "A text description of an image, used by screen readers and by image search."),

    # --- authority ---
    ("internal linking", [], 2, "Links between pages on the same site. Distributes authority and signals which pages matter."),
    ("anchor text", [], 1, "The visible, clickable words in a link. Describes what the destination is about."),
    ("backlink", ["inbound link"], 1, "A link from another site pointing at yours. A long-standing signal of authority."),
    ("link equity", ["link juice"], 2, "The ranking value passed through a link. Divided among the links on a page."),
    ("domain authority", ["DA"], 2, "A third-party score estimating a domain's ranking strength. Useful for comparison, not a Google metric."),
    ("digital PR", [], 2, "Earning coverage and links from publications through newsworthy material rather than outreach at volume."),
    ("toxic backlink", [], 2, "A link from a manipulative or low-quality source. Usually ignored rather than penalised."),
    ("brand mention", [], 2, "A reference to a brand without a link. Contributes to entity confidence even absent link equity."),

    # --- AI and retrieval ---
    ("GEO", ["generative engine optimization"], 2, "Optimizing for inclusion and citation in generative search answers rather than classic ranked links."),
    ("AEO", ["answer engine optimization"], 2, "Optimizing to be the answer an assistant returns, rather than a link a user clicks."),
    ("AI Overviews", [], 2, "Google's generated summaries shown above traditional results, assembled from retrieved pages."),
    ("RAG", [], 2, "Retrieval-augmented generation. Retrieving source documents at query time and generating an answer grounded in them."),
    ("query fan-out", [], 2, "When a system decomposes one query into several sub-questions and retrieves against each."),
    ("chunking", ["content chunking"], 2, "Splitting content into passages for retrieval. Chunk boundaries decide what can be retrieved independently."),
    ("embedding", [], 2, "A numeric vector representing meaning, letting systems compare passages by similarity rather than keyword overlap."),
    ("vector search", ["semantic search"], 2, "Retrieval by meaning similarity rather than exact term matching."),
    ("citation", [], 2, "A generated answer's attribution to a source page. The GEO equivalent of a ranking position."),
    ("hallucination", [], 2, "A confident model output unsupported by any source. Grounding in retrieved documents reduces but does not remove it."),
    ("llms.txt", [], 2, "A proposed root-level file offering LLM-oriented site guidance. Adoption and effect remain contested."),
    ("AI crawler", [], 2, "A bot collecting content for model training or retrieval, distinct from a search indexing crawler."),
    ("grounding", [], 2, "Constraining a generated answer to retrieved source material so claims can be traced."),

    # --- measurement ---
    ("Google Search Console", ["GSC"], 2, "Google's first-party reporting for impressions, clicks, indexing, and technical issues."),
    ("GA4", [], 2, "The current version of Google Analytics, built on an event-based data model."),
    ("attribution", [], 2, "Assigning credit for a conversion across the touchpoints that preceded it."),
    ("share of voice", [], 2, "A brand's visibility across a tracked keyword set relative to competitors."),
    ("conversion rate", [], 1, "The share of visitors who complete a target action."),
    ("bounce rate", [], 2, "The share of sessions with no qualifying engagement. Directional, and easy to misread."),
]

AGENTIC = [
    ("MCP", ["Model Context Protocol"], 2, "Standardizes how an AI host discovers tools, resources, and prompts from external systems, so each integration is not custom-built per client."),
    ("WebMCP", [], 2, "Lets a website declare structured tool APIs in-page through browser-mediated capabilities, reducing brittle DOM automation. A W3C community proposal."),
    ("A2A", ["Agent2Agent"], 2, "Standardizes capability discovery, task lifecycle, and cross-agent messaging so agents interoperate regardless of vendor stack."),
    ("UCP", ["Universal Commerce Protocol"], 2, "Standardizes commerce capabilities and negotiation so platforms, merchants, and payment handlers can transact in agentic interfaces."),
    ("ACP", [], 2, "An overloaded acronym. Confirm whether a source means the commerce protocol or the agent-communication one before implementing."),
    ("NLWeb", ["Natural Language Web"], 2, "Turns a site into a natural-language queryable endpoint. Agents post a question and receive structured JSON instead of scraping HTML. Every NLWeb instance is also an MCP server."),
    ("AP2", [], 2, "An agent payments protocol, designed to sit alongside A2A and MCP in commerce flows."),
    ("agentic commerce", [], 2, "Purchases discovered, negotiated, or completed by an AI agent acting for a person."),
    ("browser agent", [], 2, "An AI agent that navigates and acts on websites through a real browser session."),
    ("tool use", ["function calling"], 2, "A model invoking an external function or API rather than answering from its own parameters."),
    ("agent card", [], 2, "A machine-readable description of an agent's capabilities, used for discovery in A2A."),
    ("capability discovery", [], 2, "How one system learns what another can do before calling it."),
    ("MCP server", [], 2, "A service exposing tools and resources to AI hosts over the Model Context Protocol."),
    ("MCP client", ["MCP host"], 2, "The application connecting a model to MCP servers and mediating tool calls."),
    ("agents.json", [], 2, "A proposed manifest describing a site's APIs and workflows so agents can discover and execute them."),
    ("Web Bot Auth", [], 2, "A proposal for cryptographically identifying legitimate bots to the sites they visit."),
    ("x402", [], 2, "A proposal reviving the HTTP 402 status code for machine-to-machine payment flows."),
    ("AGENTS.md", [], 2, "A repository convention giving coding agents project-specific instructions."),
    ("autonomous agent", [], 2, "A system that plans and executes multi-step tasks toward a goal with limited human input."),
    ("human in the loop", ["HITL"], 2, "Requiring human approval at defined points in an otherwise automated process."),
    ("agent orchestration", [], 2, "Coordinating multiple specialised agents on parts of one task."),
    ("structured output", [], 2, "Constraining a model's response to a schema so downstream systems can parse it reliably."),
    ("context window", [], 2, "The amount of text a model can consider at once, spanning input and output."),
    ("prompt injection", [], 2, "An attack embedding instructions in content a model reads, hijacking its behaviour."),
    ("machine-readable", [], 2, "Structured so a program can parse meaning without inference. The prerequisite for agent consumption."),
]
