"""Regulated verticals. Industry and marketing vocabulary only.

These packs deliberately contain no advice. A definition explains what a term
means; it never tells a reader what to do about their own money, health, legal
position, or coverage. Definitions here should stay descriptive for that reason.
"""

FINANCE = [
    # --- rates and lending ---
    ("APR", [], 1, "The yearly cost of borrowing including interest and most fees, expressed as a percentage."),
    ("APY", [], 1, "The yearly return on savings including compounding. Distinct from a simple interest rate."),
    ("basis point", ["bps"], 1, "One hundredth of a percentage point. Fifty basis points is half a percent."),
    ("prime rate", [], 2, "The reference rate banks quote to their most creditworthy borrowers."),
    ("fixed rate", [], 2, "An interest rate that does not change over the life of a loan."),
    ("variable rate", ["adjustable rate"], 2, "An interest rate that moves with an underlying index."),
    ("underwriting", [], 2, "Assessing the risk of a loan or policy and deciding the terms on which to accept it."),
    ("credit score", [], 2, "A model output summarizing credit risk from a borrower's history."),
    ("LTV ratio", ["loan-to-value"], 2, "The loan amount divided by the value of the asset securing it."),
    ("DTI", ["debt-to-income"], 2, "Monthly debt payments divided by gross monthly income. A common lending threshold."),
    ("amortization", [], 2, "Paying down a balance through scheduled payments that cover both interest and principal."),
    ("principal", [], 1, "The amount borrowed, separate from the interest charged on it."),
    ("origination fee", [], 2, "A charge for processing a new loan, usually a percentage of the amount."),
    ("refinance", [], 2, "Replacing an existing loan with a new one, usually for a different rate or term."),
    ("collateral", [], 2, "An asset pledged against a loan, which the lender may claim on default."),
    ("secured loan", [], 2, "Borrowing backed by collateral. Generally cheaper than unsecured borrowing."),
    ("default", [], 2, "Failure to meet the agreed obligations of a debt."),
    ("delinquency", [], 2, "A payment past due but not yet in default."),
    ("escrow", [], 2, "Funds held by a third party until the conditions of an agreement are met."),

    # --- investing ---
    ("AUM", [], 1, "Assets under management. The total market value of assets a firm manages for clients."),
    ("expense ratio", [], 2, "The annual percentage of assets a fund charges to cover its operating costs."),
    ("liquidity", [], 2, "How quickly an asset can be converted to cash without materially moving its price."),
    ("diversification", [], 2, "Spreading exposure across assets so no single outcome dominates the result."),
    ("asset allocation", [], 2, "How a portfolio is divided across asset classes."),
    ("volatility", [], 2, "How much a price fluctuates over time. A common proxy for risk."),
    ("yield", [], 1, "Income from an investment expressed as a percentage of its price."),
    ("capital gain", [], 2, "The profit realized when an asset sells above its purchase price."),
    ("cost basis", [], 2, "The original purchase value used to calculate gain or loss on sale."),
    ("fiduciary", [], 2, "A party legally obliged to act in another's interest ahead of its own."),
    ("suitability", [], 2, "A standard requiring a recommendation to fit a client's circumstances. A lower bar than fiduciary duty."),
    ("prospectus", [], 2, "The formal disclosure document describing an investment offering."),
    ("index fund", [], 2, "A fund tracking a market index rather than selecting holdings actively."),
    ("ETF", [], 2, "Exchange-traded fund. A pooled fund whose shares trade on an exchange throughout the day."),

    # --- compliance and operations ---
    ("KYC", [], 2, "Know your customer. Regulated identity verification performed before opening an account."),
    ("AML", [], 2, "Anti-money laundering. Controls and reporting designed to detect illicit funds moving through a business."),
    ("compliance", [], 2, "The function ensuring a business meets its regulatory and legal obligations."),
    ("PCI DSS", [], 2, "The security standard governing how card data is stored, processed, and transmitted."),
    ("chargeback", [], 2, "A forced reversal of a card payment initiated by the cardholder's bank."),
    ("open banking", [], 2, "Regulated sharing of bank data with third parties through APIs, at the customer's direction."),
    ("embedded finance", [], 2, "Financial products delivered inside a non-financial company's product experience."),
    ("ACH", [], 2, "The US network for batched bank-to-bank transfers. Cheaper and slower than card rails."),
    ("wire transfer", [], 2, "A direct bank-to-bank transfer, typically same day and irreversible."),
    ("settlement", [], 2, "The point at which a transaction's funds actually move between parties."),
    ("reconciliation", [], 2, "Matching internal records against external statements to confirm they agree."),
    ("audit trail", [], 2, "A tamper-evident record of who did what and when."),
    ("Reg BI", [], 2, "A US rule requiring broker-dealers to act in a retail customer's best interest when recommending."),
    ("disclosure", [], 2, "Required published information about risks, fees, or conflicts."),
    ("financial promotion", [], 2, "A regulated communication inviting investment activity. Subject to approval rules in many jurisdictions."),

    # --- business finance ---
    ("EBITDA", [], 2, "Earnings before interest, tax, depreciation, and amortization. A rough proxy for operating cash generation."),
    ("working capital", [], 2, "Current assets minus current liabilities. What funds day-to-day operations."),
    ("runway", [], 2, "How long a business can operate at its current burn rate before it needs more capital."),
    ("cash flow", [], 1, "Money actually moving in and out, as distinct from revenue booked."),
    ("accounts receivable", ["AR"], 2, "Money owed to a business by its customers."),
]

HEALTHCARE = [
    # --- regulation and privacy ---
    ("HIPAA", [], 2, "The US law governing the privacy and security of protected health information."),
    ("PHI", [], 2, "Protected health information. Individually identifiable health data covered by HIPAA."),
    ("BAA", [], 2, "Business associate agreement. The contract required before a vendor may handle PHI."),
    ("de-identification", [], 2, "Removing identifiers from health data so it falls outside PHI rules."),
    ("consent", [], 2, "A patient's documented permission for a specified use of their data or care."),
    ("YMYL", [], 2, "Your Money or Your Life. Topics where inaccuracy could cause real harm, held to a higher content quality bar."),
    ("medical review", [], 2, "Having a qualified clinician verify health content before publication. Expected practice for health pages."),
    ("FDA clearance", [], 2, "A regulatory pathway permitting a device to be marketed in the US. Distinct from approval."),
    ("FDA approval", [], 2, "A regulatory determination that a product's benefits outweigh its risks for a stated use."),
    ("off-label", [], 2, "Use of an approved product for an indication it was not approved for. Promoting it is restricted."),

    # --- systems and data ---
    ("EHR", ["electronic health record", "EMR"], 2, "The digital record of a patient's care held by a provider organization."),
    ("interoperability", [], 2, "The ability of health systems to exchange data and use what they receive."),
    ("FHIR", [], 2, "A standard for exchanging healthcare data over web APIs."),
    ("HL7", [], 2, "A family of standards for exchanging clinical and administrative data between systems."),
    ("ICD-10", [], 2, "The international classification system used to code diagnoses."),
    ("CPT code", [], 2, "A standardized code identifying a medical procedure for billing purposes."),
    ("NPI", [], 2, "National provider identifier. The unique number assigned to a US healthcare provider."),
    ("HIE", [], 2, "Health information exchange. Infrastructure for sharing records across organizations."),
    ("patient portal", [], 2, "The interface where patients view records, results, and messages."),

    # --- payers and delivery ---
    ("payer", [], 2, "The organization that pays for care, typically an insurer or government program."),
    ("provider", [], 2, "The organization or clinician delivering care."),
    ("CMS", [], 2, "The US agency administering Medicare and Medicaid."),
    ("Medicare", [], 2, "The US federal health program primarily covering people 65 and over."),
    ("Medicaid", [], 2, "The joint US federal and state program covering people with limited income."),
    ("prior authorization", [], 2, "Approval a payer requires before it will cover a service or medication."),
    ("claim denial", [], 2, "A payer's refusal to reimburse a submitted claim."),
    ("revenue cycle", ["RCM"], 2, "The administrative process from patient registration through final payment."),
    ("in-network", [], 2, "A provider with a negotiated contract with a given payer."),
    ("value-based care", [], 2, "Reimbursement tied to patient outcomes rather than volume of services delivered."),
    ("fee-for-service", [], 2, "Reimbursement per service delivered. The model value-based care is intended to replace."),
    ("capitation", [], 2, "Paying a provider a fixed amount per patient per period regardless of services used."),
    ("population health", [], 2, "Managing outcomes across a defined group rather than one patient at a time."),
    ("care gap", [], 2, "A difference between recommended care and the care a patient has actually received."),
    ("care coordination", [], 2, "Organizing a patient's care across multiple providers and settings."),
    ("telehealth", [], 2, "Delivering care remotely by video, phone, or asynchronous messaging."),
    ("SDOH", [], 2, "Social determinants of health. Non-clinical conditions such as housing or food access that affect outcomes."),
    ("readmission", [], 2, "A patient returning to hospital shortly after discharge. A tracked quality measure."),

    # --- research and marketing ---
    ("clinical trial", [], 2, "A structured study evaluating an intervention in human participants."),
    ("IRB", [], 2, "Institutional review board. The body reviewing research protocols for participant protection."),
    ("peer review", [], 2, "Evaluation of research by independent experts before publication."),
    ("systematic review", [], 2, "A structured synthesis of all studies meeting stated criteria on a question."),
    ("evidence hierarchy", [], 2, "The ranking of study designs by strength of evidence."),
    ("patient acquisition", [], 2, "The marketing function bringing new patients to a practice or health system."),
    ("service line", [], 2, "A grouping of related clinical services managed as a unit, such as cardiology."),
    ("provider directory", [], 2, "The listing of clinicians and their details. A common source of inaccurate local data."),
    ("health literacy", [], 2, "How well a person can find, understand, and use health information."),
    ("plain language", [], 2, "Writing calibrated so the intended reader understands it on first reading. A regulatory expectation in patient materials."),
]

LEGAL = [
    # --- contracts ---
    ("indemnity", ["indemnification"], 2, "A promise by one party to cover specified losses suffered by another."),
    ("limitation of liability", [], 2, "A clause capping what one party can owe the other if things go wrong."),
    ("force majeure", [], 2, "A clause excusing performance when specified extraordinary events prevent it."),
    ("warranty", [], 2, "A contractual promise that a stated fact is true, with remedies if it is not."),
    ("representation", [], 2, "A statement of fact made to induce another party to enter an agreement."),
    ("covenant", [], 2, "A contractual promise to do or refrain from doing something."),
    ("consideration", [], 2, "The thing of value each side gives, without which a contract is generally unenforceable."),
    ("term and termination", [], 2, "The clauses setting how long an agreement runs and how it can be ended."),
    ("assignment", [], 2, "Transferring contractual rights or obligations to a third party."),
    ("governing law", [], 2, "The jurisdiction whose law will be used to interpret an agreement."),
    ("arbitration", [], 2, "Private dispute resolution before a neutral decision-maker instead of a court."),
    ("NDA", ["non-disclosure agreement"], 2, "An agreement restricting disclosure of information shared between parties."),
    ("MSA", ["master services agreement"], 2, "An umbrella contract setting standing terms, with specific work defined in separate orders."),
    ("SOW", ["statement of work"], 2, "A document defining scope, deliverables, and timelines under a master agreement."),
    ("DPA", ["data processing agreement"], 2, "A contract governing how a vendor handles personal data on a customer's behalf."),
    ("SLA", ["service level agreement"], 2, "A commitment to defined service standards, usually with remedies for shortfalls."),
    ("boilerplate", [], 2, "Standard clauses appearing in most agreements. Routine, and occasionally consequential."),
    ("redline", [], 2, "A marked-up draft showing proposed changes between negotiating parties."),
    ("execution", [], 2, "The signing that makes an agreement binding."),

    # --- entities and disputes ---
    ("LLC", [], 2, "Limited liability company. A US structure combining liability protection with pass-through taxation."),
    ("incorporation", [], 2, "Forming a company as a legal entity separate from its owners."),
    ("registered agent", [], 2, "The party designated to receive legal notices on a company's behalf."),
    ("due diligence", [], 2, "Investigation of a counterparty or asset before committing to a transaction."),
    ("litigation", [], 2, "Resolving a dispute through the courts."),
    ("discovery", [], 2, "The pre-trial phase in which parties exchange relevant evidence."),
    ("deposition", [], 2, "Sworn out-of-court testimony taken during discovery."),
    ("settlement", [], 2, "An agreed resolution ending a dispute without a judgment."),
    ("injunction", [], 2, "A court order requiring a party to do or stop doing something."),
    ("statute of limitations", [], 2, "The deadline after which a claim can no longer be brought."),
    ("class action", [], 2, "A suit brought by representatives on behalf of a larger group with common claims."),
    ("privilege", ["attorney-client privilege"], 2, "Protection from compelled disclosure of confidential legal advice."),
    ("conflict of interest", [], 2, "A situation where duties to one client could compromise duties to another."),
    ("retainer", [], 2, "An advance payment securing legal services."),
    ("billable hour", [], 2, "The standard unit of legal billing. Increasingly supplemented by fixed-fee arrangements."),

    # --- IP and data ---
    ("intellectual property", ["IP"], 2, "Legally protected creations: patents, trademarks, copyrights, and trade secrets."),
    ("trademark", [], 2, "A protected mark identifying the source of goods or services."),
    ("copyright", [], 2, "Protection for original works of authorship, arising automatically on creation."),
    ("patent", [], 2, "A time-limited exclusive right over an invention, granted in exchange for disclosure."),
    ("trade secret", [], 2, "Commercially valuable information protected by being kept confidential."),
    ("fair use", [], 2, "A US doctrine permitting some unlicensed use of copyrighted work. Fact-specific and decided case by case."),
    ("licence", ["license"], 2, "Permission to use protected material on stated terms."),
    ("GDPR", [], 2, "The EU regulation governing personal data processing, with extraterritorial reach."),
    ("CCPA", [], 2, "California's consumer privacy law, granting access, deletion, and opt-out rights."),
    ("data subject request", ["DSAR"], 2, "An individual's request to access, correct, or delete data held about them."),
    ("processor", [], 2, "A party handling personal data on behalf of, and under instruction from, a controller."),
    ("controller", [], 2, "The party determining the purposes and means of processing personal data."),
    ("breach notification", [], 2, "The regulated obligation to inform authorities and affected people after a data breach."),
    ("records retention", [], 2, "The policy governing how long records are kept and when they are destroyed."),
    ("legal hold", [], 2, "A directive suspending routine deletion when litigation is anticipated."),
    ("compliance program", [], 2, "The structured set of policies, training, and monitoring used to meet legal obligations."),
]

INSURANCE = [
    ("premium", [], 1, "The amount paid for insurance coverage, usually monthly or annually."),
    ("deductible", [], 1, "The amount an insured pays out of pocket before coverage begins to pay."),
    ("copay", [], 2, "A fixed amount paid for a covered service, separate from the deductible."),
    ("coinsurance", [], 2, "The percentage of a covered cost the insured pays after the deductible is met."),
    ("out-of-pocket maximum", [], 2, "The annual ceiling on what an insured pays before coverage pays everything else."),
    ("policy limit", [], 2, "The maximum an insurer will pay under a policy."),
    ("rider", ["endorsement"], 2, "An add-on modifying the coverage of a base policy."),
    ("exclusion", [], 2, "A circumstance a policy explicitly does not cover."),
    ("underwriting", [], 2, "Assessing the risk of insuring someone and setting terms accordingly."),
    ("actuary", [], 2, "A specialist who models risk and prices it using statistical methods."),
    ("loss ratio", [], 2, "Claims paid as a proportion of premiums collected."),
    ("combined ratio", [], 2, "Claims plus expenses as a proportion of premiums. Below 100% means underwriting profit."),
    ("claim", [], 1, "A request for payment under the terms of a policy."),
    ("adjuster", [], 2, "The person who investigates a claim and determines what the insurer owes."),
    ("subrogation", [], 2, "An insurer pursuing a third party responsible for a loss it has paid out."),
    ("first-party claim", [], 2, "A claim made by the policyholder against their own insurer."),
    ("third-party claim", [], 2, "A claim made against a policyholder by someone else."),
    ("reinsurance", [], 2, "Insurance bought by insurers to cap their own exposure."),
    ("captive insurer", [], 2, "An insurance subsidiary formed to cover its parent company's risks."),
    ("broker", [], 2, "An intermediary representing the buyer when placing coverage."),
    ("agent", ["insurance agent"], 2, "An intermediary representing the insurer when selling coverage."),
    ("carrier", [], 2, "The company actually bearing the insured risk."),
    ("open enrollment", [], 2, "The defined window during which coverage may be selected or changed."),
    ("qualifying life event", [], 2, "A change permitting a coverage election outside open enrollment."),
    ("in-network", [], 2, "A provider with a negotiated contract with the insurer."),
    ("EOB", [], 2, "Explanation of benefits. The statement showing what was billed, covered, and owed. Not a bill."),
    ("formulary", [], 2, "The list of medications a health plan covers, usually organized in cost tiers."),
    ("umbrella policy", [], 2, "Additional liability coverage sitting above the limits of underlying policies."),
    ("named perils", [], 2, "A policy covering only the specific risks it lists."),
    ("all risk", ["open perils"], 2, "A policy covering any risk except those explicitly excluded."),
    ("replacement cost", [], 2, "Coverage paying to replace property without deducting for depreciation."),
    ("actual cash value", ["ACV"], 2, "Coverage paying replacement cost minus depreciation."),
    ("proof of loss", [], 2, "The documentation an insured submits to substantiate a claim."),
    ("lapse", [], 2, "Coverage ending because premiums were not paid."),
    ("grace period", [], 2, "A window after a missed payment during which coverage continues."),
    ("risk pool", [], 2, "The group across which insured risk is spread."),
    ("adverse selection", [], 2, "When higher-risk people are disproportionately likely to buy coverage, pushing prices up."),
    ("moral hazard", [], 2, "The tendency to take more risk once insured against its consequences."),
    ("insurtech", [], 2, "Technology-led entrants and tools reshaping insurance distribution and underwriting."),
    ("embedded insurance", [], 2, "Coverage offered inside another purchase, such as at checkout."),
]
