"""Property, local services, industrial, hospitality, education, automotive."""

REAL_ESTATE = [
    ("MLS", [], 2, "Multiple listing service. The shared database brokers use to list and search properties in a market."),
    ("IDX", [], 2, "Internet data exchange. The framework letting brokers publish MLS listings on their own websites."),
    ("comps", ["comparables"], 2, "Recently sold similar properties used to estimate what a home is worth."),
    ("CMA", [], 2, "Comparative market analysis. An agent's valuation estimate built from comparable sales."),
    ("appraisal", [], 2, "A licensed valuation of a property, usually required by a lender."),
    ("days on market", ["DOM"], 1, "How long a listing has been active before going under contract."),
    ("absorption rate", [], 2, "How quickly available inventory sells in a market, usually expressed in months of supply."),
    ("under contract", [], 2, "An accepted offer with conditions still outstanding, so the sale is not yet complete."),
    ("contingency", [], 2, "A condition that must be met before a sale closes, such as financing or inspection."),
    ("escrow", [], 2, "Funds or documents held by a neutral third party until closing conditions are met."),
    ("closing costs", [], 2, "Fees paid at completion, covering lending, title, and transfer charges."),
    ("title insurance", [], 2, "Coverage protecting against defects in a property's ownership history."),
    ("lien", [], 2, "A legal claim against a property securing a debt."),
    ("deed", [], 2, "The instrument transferring ownership of real property."),
    ("earnest money", [], 2, "A deposit showing a buyer's good faith, credited at closing."),
    ("pre-approval", [], 2, "A lender's conditional commitment to a loan amount, based on verified financials."),
    ("PMI", [], 2, "Private mortgage insurance. Required by lenders when a down payment falls below a threshold."),
    ("HOA", [], 2, "Homeowners association. The body governing shared areas and rules in a community, funded by member dues."),
    ("zoning", [], 2, "Local rules dictating how a parcel of land may be used and what may be built on it."),
    ("variance", [], 2, "Permission to depart from zoning rules for a specific property."),
    ("easement", [], 2, "A right for someone else to use part of a property for a defined purpose."),
    ("setback", [], 2, "The minimum required distance between a structure and a property line."),
    ("cap rate", ["capitalization rate"], 2, "Net operating income divided by property value. A yield measure for income property."),
    ("NOI", [], 1, "Net operating income. Rental income less operating expenses, before debt service and taxes."),
    ("cash on cash return", [], 2, "Annual pre-tax cash flow divided by the cash actually invested."),
    ("DSCR", [], 2, "Debt service coverage ratio. Net operating income divided by debt payments."),
    ("1031 exchange", [], 2, "A US provision deferring capital gains tax when sale proceeds are reinvested in like-kind property."),
    ("triple net lease", ["NNN"], 2, "A commercial lease where the tenant pays taxes, insurance, and maintenance on top of rent."),
    ("gross lease", [], 2, "A lease where the landlord covers operating expenses out of the rent."),
    ("tenant improvement", ["TI"], 2, "Work done to fit a commercial space to a tenant's needs, often funded by an allowance."),
    ("vacancy rate", [], 2, "The share of rentable space sitting empty."),
    ("class A", [], 2, "The top tier of commercial property quality, by age, location, and finish."),
    ("cap ex", ["capital expenditure"], 2, "Spending on improvements that extend a property's life or value, as distinct from routine repairs."),
    ("property management", [], 2, "Day-to-day operation of a property on the owner's behalf."),
    ("iBuyer", [], 2, "A company making algorithmic instant cash offers on homes."),
    ("pocket listing", [], 2, "A property marketed privately rather than through the MLS."),
    ("dual agency", [], 2, "One agent or brokerage representing both sides of a transaction. Restricted or barred in some jurisdictions."),
    ("Google Business Profile", ["GBP"], 2, "The listing controlling how a business appears in maps and local results."),
    ("geo page", [], 2, "A location-targeted landing page. Valuable when genuinely local, thin when templated across towns."),
    ("farming", [], 2, "Concentrating marketing on one geographic area to build recognition over time."),
]

HOME_SERVICES = [
    ("service area", [], 2, "The geographic region a business will travel to serve. Defines realistic local targeting."),
    ("SAB", ["service area business"], 2, "A business serving customers at their location rather than at a storefront. Listed without a public address."),
    ("Google Business Profile", ["GBP"], 2, "The listing controlling how a business appears in maps and local results."),
    ("local pack", ["map pack"], 2, "The map plus three business listings shown for local-intent queries."),
    ("NAP", [], 2, "Name, address, phone. Consistency across listings is a core local ranking signal."),
    ("citation", ["local citation"], 2, "A mention of a business's name, address, and phone on a directory or site."),
    ("proximity", [], 2, "How close a searcher is to a business. Usually the strongest local ranking factor, and the one you cannot change."),
    ("review velocity", [], 2, "How quickly new reviews arrive. Steadier matters more than bursty."),
    ("review gating", [], 2, "Soliciting reviews only from satisfied customers. Prohibited by most major platforms."),
    ("LSA", ["Local Services Ads"], 2, "Google's pay-per-lead ad format for service businesses, requiring background screening."),
    ("Google Guaranteed", [], 2, "A badge on Local Services Ads indicating screening and a limited job-value guarantee."),
    ("lead", [], 1, "A prospective customer who has made contact but not yet booked."),
    ("cost per lead", ["CPL"], 1, "Marketing spend divided by leads generated."),
    ("booked job rate", [], 2, "The share of leads that convert into scheduled work."),
    ("average ticket", [], 2, "Average revenue per completed job."),
    ("truck roll", [], 2, "Sending a technician to a site. The main unit of cost in field service."),
    ("first-time fix rate", [], 2, "The share of jobs resolved on the first visit."),
    ("dispatch", [], 2, "Assigning and routing technicians to jobs."),
    ("field service management", ["FSM"], 2, "Software coordinating scheduling, dispatch, and invoicing for mobile crews."),
    ("estimate", ["quote"], 1, "A priced proposal for work, given before the job is accepted."),
    ("change order", [], 2, "A documented adjustment to agreed scope and price mid-job."),
    ("callback", [], 2, "A return visit to correct earlier work. Usually unpaid, and a direct margin loss."),
    ("warranty work", [], 2, "Repairs performed under an existing guarantee."),
    ("maintenance agreement", ["service plan"], 2, "A recurring contract for scheduled servicing. The main route to predictable revenue in trades."),
    ("preventive maintenance", [], 2, "Scheduled servicing intended to avoid failures rather than respond to them."),
    ("emergency call-out", [], 2, "Unscheduled urgent work, usually priced at a premium."),
    ("licensed and bonded", [], 2, "Holding the required trade licence and a surety bond covering incomplete or defective work."),
    ("permit", [], 2, "Municipal authorization required before certain work may legally proceed."),
    ("inspection", [], 2, "An official check that completed work meets code."),
    ("code compliance", [], 2, "Conformance with the building or trade standards in force locally."),
    ("HVAC", [], 2, "Heating, ventilation, and air conditioning."),
    ("SEER", [], 2, "Seasonal energy efficiency ratio. A cooling efficiency rating for HVAC equipment."),
    ("hard water", [], 2, "Water with high mineral content, which scales fixtures and shortens appliance life."),
    ("backflow prevention", [], 2, "A device stopping contaminated water re-entering a clean supply."),
    ("load calculation", [], 2, "Sizing equipment to a building's actual heating or cooling demand rather than by rule of thumb."),
    ("seasonality", [], 2, "Predictable demand swings across the year. The defining planning problem in most trades."),
    ("referral rate", [], 2, "The share of new work arriving through existing customers."),
    ("before and after", [], 2, "Paired photos documenting completed work. The highest-converting content type in most trades."),
]

MANUFACTURING = [
    ("OEM", [], 2, "Original equipment manufacturer. The company that produced a part or system under its own name."),
    ("ODM", [], 2, "Original design manufacturer. A supplier that designs as well as builds, for another brand to sell."),
    ("contract manufacturing", [], 2, "Outsourced production to a supplier's specification and capacity."),
    ("BOM", ["bill of materials"], 2, "The structured list of every component required to build a product."),
    ("MOQ", [], 2, "Minimum order quantity. The smallest batch a supplier will produce."),
    ("manufacturing lead time", ["production lead time"], 1, "Elapsed time from placing an order to receiving it."),
    ("takt time", [], 2, "The production pace required to meet customer demand."),
    ("cycle time", [], 2, "How long one unit takes to move through a process."),
    ("throughput", [], 1, "Units produced per unit of time."),
    ("OEE", [], 2, "Overall equipment effectiveness. Availability times performance times quality."),
    ("process yield", ["first pass yield"], 2, "The share of units produced that meet specification."),
    ("scrap rate", [], 2, "The share of material lost to defects or waste."),
    ("rework", [], 2, "Correcting defective output rather than scrapping it."),
    ("tolerance", [], 2, "The permitted deviation from a specified dimension."),
    ("GD&T", [], 2, "Geometric dimensioning and tolerancing. A standard notation for specifying allowable variation."),
    ("CNC", [], 2, "Computer numerical control. Machining driven by programmed instructions."),
    ("CAD", [], 2, "Computer-aided design. Software for producing engineering drawings and models."),
    ("CAM", [], 2, "Computer-aided manufacturing. Software translating designs into machine instructions."),
    ("additive manufacturing", ["3D printing"], 2, "Building parts by adding material layer by layer rather than cutting it away."),
    ("injection moulding", ["injection molding"], 2, "Forming parts by forcing molten material into a tool. High tooling cost, low unit cost at volume."),
    ("tooling", [], 2, "The dies, moulds, and fixtures required to produce a part."),
    ("prototype", [], 2, "An early build used to validate design before committing to production tooling."),
    ("new product introduction", ["NPI process"], 2, "Taking a design from validated prototype into stable production. Distinct from the healthcare NPI, which is a provider identifier."),
    ("lean manufacturing", [], 2, "A method focused on removing activity that does not add customer value."),
    ("Six Sigma", [], 2, "A method for reducing process variation using statistical analysis."),
    ("kaizen", [], 2, "Continuous incremental improvement driven by the people doing the work."),
    ("kanban", [], 2, "A pull-based signalling system that triggers replenishment only when stock is consumed."),
    ("just in time", ["JIT"], 2, "Receiving material only as production needs it. Efficient, and fragile under supply shock."),
    ("MRP", [], 2, "Material requirements planning. Scheduling purchases and production from a demand forecast."),
    ("ERP", [], 2, "Enterprise resource planning. The system of record spanning finance, inventory, and production."),
    ("MES", [], 2, "Manufacturing execution system. Software tracking and controlling work on the shop floor."),
    ("SCADA", [], 2, "Supervisory control and data acquisition. Systems monitoring and controlling industrial equipment."),
    ("PLC", [], 2, "Programmable logic controller. The industrial computer running machine control logic."),
    ("predictive maintenance", [], 2, "Using condition data to service equipment before it fails."),
    ("ISO 9001", [], 2, "The international standard for quality management systems."),
    ("traceability", [], 2, "The ability to follow a part's history through materials, process, and handling."),
    ("supply chain resilience", [], 2, "The capacity to keep producing when a supplier, route, or input fails."),
    ("nearshoring", [], 2, "Relocating production closer to the end market to shorten and de-risk supply."),
    ("spec sheet", ["datasheet"], 2, "The document stating a product's dimensions, materials, and performance. High-intent content in industrial search."),
    ("RFQ", [], 2, "Request for quote. A buyer's formal request for pricing against a specification."),
]

HOSPITALITY = [
    ("ADR", [], 2, "Average daily rate. Room revenue divided by rooms sold."),
    ("RevPAR", [], 2, "Revenue per available room. Occupancy multiplied by average daily rate."),
    ("occupancy rate", [], 1, "The share of available rooms sold in a period."),
    ("TRevPAR", [], 2, "Total revenue per available room, including food, beverage, and other spend."),
    ("GOPPAR", [], 2, "Gross operating profit per available room. A profitability rather than revenue measure."),
    ("length of stay", ["LOS"], 2, "Average nights per booking. Longer stays lower servicing cost per night."),
    ("booking window", ["booking lead time"], 2, "How far ahead of arrival a reservation is made."),
    ("OTA", [], 2, "Online travel agency. A third-party booking channel charging commission per reservation."),
    ("direct booking", [], 2, "A reservation made through the property's own channels, avoiding commission."),
    ("rate parity", [], 2, "Keeping published rates consistent across distribution channels."),
    ("channel manager", [], 2, "Software syncing availability and rates across booking channels."),
    ("PMS", [], 2, "Property management system. The operational system of record for reservations and rooms."),
    ("CRS", [], 2, "Central reservation system. The hub distributing inventory to booking channels."),
    ("GDS", [], 2, "Global distribution system. The legacy network travel agents use to book inventory."),
    ("yield management", ["revenue management"], 2, "Adjusting price and availability by demand to maximise revenue rather than occupancy."),
    ("overbooking", [], 2, "Deliberately accepting more reservations than rooms, priced against expected cancellations."),
    ("no-show", [], 2, "A confirmed guest who never arrives."),
    ("walk", [], 2, "Relocating a guest to another property when the hotel is oversold."),
    ("comp set", ["competitive set"], 2, "The group of properties a hotel benchmarks its performance against."),
    ("STR report", [], 2, "A benchmarking report comparing a property's performance against its comp set."),
    ("shoulder season", [], 2, "The period between peak and low season, with softer rates and demand."),
    ("group business", [], 2, "Bookings from conferences, weddings, and corporate blocks."),
    ("MICE", [], 2, "Meetings, incentives, conferences, and exhibitions. The organized-events segment."),
    ("F&B", [], 2, "Food and beverage. Usually the second-largest revenue line after rooms."),
    ("cover", [], 2, "One meal served to one guest. The unit of restaurant volume."),
    ("RevPASH", [], 2, "Revenue per available seat hour. The restaurant analogue of RevPAR."),
    ("front of house", [], 2, "The guest-facing part of an operation."),
    ("back of house", [], 2, "The operational areas guests do not see."),
    ("turndown", [], 2, "Evening room service preparing the room for the night."),
    ("upsell", [], 2, "Offering a higher-value option at or after booking."),
    ("ancillary revenue", [], 2, "Income beyond the core product, such as parking, spa, or late checkout."),
    ("loyalty program", [], 2, "A structured incentive rewarding repeat stays, and a major direct-booking driver."),
    ("guest satisfaction score", ["GSS"], 2, "A survey-based measure of guest experience."),
    ("review response rate", [], 2, "The share of guest reviews the property replies to. A visible trust signal."),
    ("destination content", [], 2, "Editorial about the surrounding area. Captures planning-stage intent before a property is chosen."),
    ("seasonality", [], 2, "Predictable demand swings across the year. The central planning constraint in travel."),
    ("cancellation policy", [], 2, "The terms under which a booking may be voided and what is refunded."),
    ("Hotel schema", [], 2, "Structured data describing a property's rooms, amenities, and rates for enriched search results."),
]

EDUCATION = [
    ("LMS", [], 2, "Learning management system. The platform hosting courses, assignments, and grades."),
    ("SIS", [], 2, "Student information system. The system of record for enrolment, records, and transcripts."),
    ("enrollment", ["enrolment"], 1, "The count of registered students, and the primary institutional revenue driver."),
    ("yield rate", [], 2, "The share of admitted applicants who enrol."),
    ("melt", ["summer melt"], 2, "Admitted students who commit but never arrive."),
    ("retention rate", [], 2, "The share of students continuing from one year to the next."),
    ("persistence", [], 2, "Whether a student continues in higher education anywhere, not only at one institution."),
    ("completion rate", ["graduation rate"], 2, "The share of a cohort finishing their programme within a defined window."),
    ("attrition", [], 2, "Students leaving before completion."),
    ("accreditation", [], 2, "Recognition by an authorized body that an institution meets defined standards."),
    ("articulation agreement", [], 2, "A formal arrangement letting credits transfer between institutions."),
    ("credit hour", [], 2, "The standard unit of academic workload."),
    ("cohort", [], 2, "A group progressing through a programme together."),
    ("asynchronous learning", [], 2, "Study without fixed meeting times, completed on the student's schedule."),
    ("synchronous learning", [], 2, "Instruction delivered live at a scheduled time."),
    ("blended learning", ["hybrid"], 2, "Combining in-person and online instruction."),
    ("competency-based education", ["CBE"], 2, "Progression by demonstrated mastery rather than time served."),
    ("microcredential", [], 2, "A short, targeted qualification certifying a specific skill."),
    ("stackable credential", [], 2, "A qualification that counts toward a larger one later."),
    ("bootcamp", [], 2, "An intensive short programme focused on job-ready skills."),
    ("CEU", [], 2, "Continuing education unit. A standard measure of professional development."),
    ("FAFSA", [], 2, "The US application determining eligibility for federal student financial aid."),
    ("financial aid package", [], 2, "The combination of grants, loans, and work-study offered to a student."),
    ("net price", [], 2, "Published cost minus grant aid. What a student actually pays."),
    ("Title IV", [], 2, "The US federal student aid programs, and the compliance regime attached to them."),
    ("FERPA", [], 2, "The US law governing the privacy of student education records."),
    ("Title IX", [], 2, "The US law prohibiting sex discrimination in federally funded education programs."),
    ("IPEDS", [], 2, "The US federal data collection all participating institutions must report to."),
    ("student outcomes", [], 2, "Measured results after study, such as completion, employment, and earnings."),
    ("learning outcome", [], 2, "A stated, assessable description of what a student should be able to do."),
    ("formative assessment", [], 2, "Assessment during learning, used to guide teaching rather than grade it."),
    ("summative assessment", [], 2, "Assessment at the end of a unit, used to judge achievement."),
    ("rubric", [], 2, "A published scoring guide making assessment criteria explicit."),
    ("differentiated instruction", [], 2, "Adapting teaching to varied readiness and needs within one group."),
    ("IEP", [], 2, "Individualized education program. A legally required plan for a US student with a disability."),
    ("EdTech", [], 2, "Technology built for teaching, learning, and institutional operations."),
    ("program page", [], 2, "The page describing a course of study. The highest-intent page in education search."),
    ("Course schema", [], 2, "Structured data describing a course's provider, delivery mode, and credential."),
    ("nontraditional student", [], 2, "A learner outside the school-leaver profile: older, part-time, working, or returning."),
    ("workforce development", [], 2, "Training aligned to identified employer demand in a region."),
]

AUTOMOTIVE = [
    ("VIN", [], 2, "Vehicle identification number. The unique seventeen-character identifier for a vehicle."),
    ("trim", ["trim level"], 2, "A named specification variant of a model, bundling features and options."),
    ("MSRP", [], 2, "Manufacturer's suggested retail price. The published list price before negotiation."),
    ("invoice price", [], 2, "What the dealer nominally pays the manufacturer. A negotiation reference, not full cost."),
    ("holdback", [], 2, "A manufacturer payment to a dealer after sale, below invoice price."),
    ("floor plan", [], 2, "The financing dealers use to hold inventory on the lot."),
    ("days supply", [], 2, "How long current inventory would last at the recent sales rate."),
    ("turn rate", [], 2, "How quickly inventory sells and is replaced."),
    ("front-end gross", [], 2, "Profit on the vehicle sale itself."),
    ("back-end gross", [], 2, "Profit from financing, insurance, and add-ons sold alongside the vehicle."),
    ("F&I", [], 2, "Finance and insurance. The department selling financing and protection products."),
    ("trade-in", [], 2, "A vehicle given toward the purchase of another."),
    ("ACV", ["actual cash value"], 2, "A trade-in's wholesale market value to the dealer."),
    ("reconditioning", ["recon"], 2, "Work done to prepare a used vehicle for retail sale."),
    ("CPO", ["certified pre-owned"], 2, "A used vehicle inspected and warranted under a manufacturer program."),
    ("VDP", ["vehicle detail page"], 2, "The listing page for a single vehicle. The core conversion page in automotive retail."),
    ("SRP", ["search results page"], 2, "The filterable inventory listing page on a dealer site."),
    ("lead form", [], 2, "The enquiry form on a listing. The primary conversion event for most dealers."),
    ("walkaround video", [], 2, "A recorded tour of a specific vehicle. Consistently the highest-converting listing asset."),
    ("service absorption", [], 2, "How much of a dealership's fixed cost is covered by service and parts profit."),
    ("RO", ["repair order"], 2, "The record of work performed in a service visit."),
    ("effective labor rate", [], 2, "Actual labour revenue divided by hours billed."),
    ("warranty claim", [], 2, "Reimbursement sought from a manufacturer for covered repair work."),
    ("recall", [], 2, "A manufacturer-initiated correction of a safety or compliance defect."),
    ("TSB", [], 2, "Technical service bulletin. Manufacturer guidance on a known issue, short of a recall."),
    ("OEM parts", [], 2, "Parts made by or for the vehicle manufacturer, as opposed to aftermarket equivalents."),
    ("aftermarket", [], 2, "Parts and accessories made by companies other than the vehicle manufacturer."),
    ("EV", ["electric vehicle"], 1, "A vehicle driven by electric motors and powered by a battery."),
    ("BEV", [], 2, "Battery electric vehicle. Fully electric, with no combustion engine."),
    ("PHEV", [], 2, "Plug-in hybrid electric vehicle. Combines a battery that charges externally with a combustion engine."),
    ("range anxiety", [], 2, "A buyer's concern about running out of charge before reaching a charger."),
    ("Level 2 charging", [], 2, "AC charging at 240 volts. The standard home and workplace charging speed."),
    ("DC fast charging", [], 2, "High-power direct current charging used for rapid top-ups on longer journeys."),
    ("kWh", [], 2, "Kilowatt hour. The unit of battery capacity and energy consumption."),
    ("MPGe", [], 2, "Miles per gallon equivalent. An efficiency measure letting electric and combustion vehicles be compared."),
    ("ADAS", [], 2, "Advanced driver assistance systems. Features such as lane keeping and automatic braking."),
    ("telematics", [], 2, "Vehicle data transmitted for tracking, diagnostics, or usage-based insurance."),
    ("Vehicle schema", [], 2, "Structured data describing a vehicle's specification, mileage, and price for enriched listings."),
    ("inventory feed", [], 2, "A structured export of available vehicles sent to listing sites and ad platforms."),
]
